// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qszcbdqwddrzutbxiohr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzemNiZHF3ZGRyenV0Ynhpb2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjM4NTgsImV4cCI6MjA2NDk5OTg1OH0.ETXma_X1Wiba9DUCE7WlRVOQ73K9Y1L_UeR66B6KY9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);